import GenericTemplate from "@/components/templates/GenericTemplate"
import { UserProvider } from "@/context/UserContext"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GenericTemplate>
          <UserProvider>
            {children}
          </UserProvider>
        </GenericTemplate>
      </body>
    </html>
  )
}
